mainmodel:
  task: 'DQN_CartPole-v1'
  path: 'mllib.main_models.dqn.main'
  class_name: 'DQN'
  max_train_epsd: 10000
  max_train_step: 1000000000000000
  outdir: ./runs_train
  enable_fp16: True
  discount_rate: 0.999
  #ε-greedyの確率
  random_act_prob: 0.1
  act_space: 2
  train_frq: 100
  exp_num_use: 1


#追従するモデルと、パラメータを学習するか、そしてモデルパラメータ
model:
  root: ''
  comp:
    q_net:
      name: 'DQN_network_CartPole_v1'
      enable_train: True
      opt_model: 'AdamW_0.1'
      model_params:
        no_param: True
    # cartpole_obs_edit:
    #   name: 'CartPole_obs_edit_orig'
    #   enable_train: False

#試用する環境とパラメータ
env:
  name: 'CartPole_v1'
  enable_finish_epsd: True
  max_step: 100
  env_params:
    enable_render: True

#オプティマイザーモデル選択
opt:
  adamw:
    name: 'AdamW'
    profile_name: 'AdamW_0.1'
    opt_params:
      lr: 0.01
      wd: 0.0
      adam_eps: 1.0e-8
      adam_betas: [0.0, 0.9]
  sgd:
    name: 'SGD'
    profile_name: 'SGD_defo'
    opt_params:
      lr: 0.01

log:
  print:
    step: 500
    train: 10
    epsd: 50
  bord:
    step: 100
    train: 10
    epsd: 1

info:
  blank: 'blank'