mainmodel:
  task: 'モデル名_環境名'
  path: './mllib/main_models/モデル名'
  class_name: 'モデル名'
  outdir: ./runs_train
  enable_fp16: True


#追従するモデルと、パラメータを学習するか、そしてモデルパラメータ
model:
  root: ''
  comp:
    q_net:
      name: 'model.pyにあるモデルのクラス名'
      enable_train: #パラメータを学習するか
      lr: 0.1
      hyper_params:
    cartpole_obs_edit:
      name: 'CartPole_obs_edit_orig'
      enable_train: False
      lr: None
      hyper_params:

#試用する環境とパラメータ
env:
  name: '利用する環境のenvs.pyのクラス名'

#オプティマイザーモデル選択
opt:
  name: 'オプティマイザーの名前'
  lr_warmup_ratio: 1.0
  lr_cooldown_ratio: 0.99
  gain_threshold_turn_phase: 1.0e+10
  gain_threshold_cooldown_phase: 1.0e+10

log:
  print:
    step: 100
    epsd: 10000000000
  bord:
    step: 100
    epsd: 1
