mainmodel:
  task: 'DQN_CartPole-v0'
  path: 'mllib.main_models.dqn.main'
  class_name: 'DQN'
  outdir: ./runs_train


#追従するモデルと、パラメータを学習するか、そしてモデルパラメータ
model:
  root: ''
  comp:
    q_net:
      name: 'DQN_network_orig'
      enable_train: True
      lr: 0.1
      model_params:
        no_param: True
    # cartpole_obs_edit:
    #   name: 'CartPole_obs_edit_orig'
    #   enable_train: False

#試用する環境とパラメータ
env:
  name: 'CartPole_v0'
  enable_finish_epsd: True
  enalbe_render: True
  max_epsd: 100
  env_params:
    no_param: True

#オプティマイザーモデル選択
opt:
  name: AdamW_decay
  lr_warmup_ratio: 1.0
  lr_cooldown_ratio: 0.99
  gain_threshold_turn_phase: 1.0e+10
  gain_threshold_cooldown_phase: 1.0e+10

log:
  print:
    step: 100
    epsd: 10000000000
  bord:
    step: 100
    epsd: 1

info:
  blank: 'blank'